name: params
version: 0.0.2
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Params provides 'window.location.search' on client and 'request.requestedUrl.query' on server as a Map
homepage: https://github.com/HannesRammer/Params
environment:
  sdk: '>=0.8.10+6 <2.0.0'
